/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.view;

import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.controller.ManageOrderController;
import lk.ijse.dinemore.dto.OrderDTO;
import lk.ijse.dinemore.observer.Observer;

/**
 *
 * @author Nadun
 */
public class CookingForm extends javax.swing.JFrame implements Observer{
private String reservedCustomerID ="";
    /**
     * Creates new form CookingForm
     */
    public CookingForm() {
         try {
            initComponents();
            loadAllOrders();
            UnicastRemoteObject.exportObject(this, 0);
            ManageOrderController.getSubeject()
                    .registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCooking = new javax.swing.JTable();
        buttonFinished = new javax.swing.JButton();
        buttonCooking = new javax.swing.JButton();
        txtcidCook = new java.awt.Label();
        txtNameCook = new java.awt.Label();
        txtTelCook = new java.awt.Label();
        txtQtyCook = new java.awt.Label();
        txtStatusCook = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("COOKING  MANAGING");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CUSTOMER ID", "NAME", "TELE", "QTY", "STATUS"
            }
        ));
        tableCooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCooking);

        buttonFinished.setBackground(new java.awt.Color(153, 0, 51));
        buttonFinished.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonFinished.setText("FINISHED");
        buttonFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishedActionPerformed(evt);
            }
        });

        buttonCooking.setBackground(new java.awt.Color(0, 153, 0));
        buttonCooking.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCooking.setText("COOKING");
        buttonCooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCookingActionPerformed(evt);
            }
        });

        txtcidCook.setBackground(new java.awt.Color(153, 204, 255));
        txtcidCook.setForeground(new java.awt.Color(153, 204, 255));
        txtcidCook.setText("l");

        txtNameCook.setBackground(new java.awt.Color(153, 204, 255));
        txtNameCook.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNameCook.setForeground(new java.awt.Color(153, 204, 255));

        txtTelCook.setBackground(new java.awt.Color(153, 204, 255));
        txtTelCook.setForeground(new java.awt.Color(153, 204, 255));

        txtQtyCook.setBackground(new java.awt.Color(153, 204, 255));
        txtQtyCook.setForeground(new java.awt.Color(153, 204, 255));

        txtStatusCook.setBackground(new java.awt.Color(153, 204, 255));
        txtStatusCook.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(buttonFinished, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtcidCook, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtNameCook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(txtTelCook, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(txtQtyCook, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtStatusCook, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(buttonCooking, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(412, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtyCook, javax.swing.GroupLayout.PREFERRED_SIZE, 11, Short.MAX_VALUE)
                    .addComponent(txtStatusCook, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelCook, javax.swing.GroupLayout.PREFERRED_SIZE, 11, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameCook, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcidCook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonFinished, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(443, Short.MAX_VALUE)
                    .addComponent(buttonCooking, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCookingActionPerformed
        try {
           OrderDTO orderDTO=new OrderDTO(
            txtcidCook.getText(),
            txtNameCook.getText(), 
            txtTelCook.getText(),
            Integer.parseInt(txtQtyCook.getText()),
             "COOKING"
            );
            boolean updateCustomer = ManageOrderController.updateCustomer(orderDTO);
            if (updateCustomer) {
                JOptionPane.showMessageDialog(this, "Customer has been Update Successfully");
                loadAllOrders();
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Update Customer");
            }
            ManageOrderController.releaseCustomer(reservedCustomerID);
            reservedCustomerID="";
        } catch (Exception ex) {
            Logger.getLogger(CookingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCookingActionPerformed

    private void buttonFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishedActionPerformed
        try {
           OrderDTO orderDTO=new OrderDTO(
            txtcidCook.getText(),
            txtNameCook.getText(), 
            txtTelCook.getText(),
            Integer.parseInt(txtQtyCook.getText()),
             "COOKED"
            );
            boolean updateCustomer = ManageOrderController.updateCustomer(orderDTO);
            if (updateCustomer) {
                JOptionPane.showMessageDialog(this, "Customer has been Update Successfully");
                loadAllOrders();
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Update Customer");
            }
            ManageOrderController.releaseCustomer(reservedCustomerID);
            reservedCustomerID="";
        } catch (Exception ex) {
            Logger.getLogger(CookingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonFinishedActionPerformed

    private void tableCookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCookingMouseClicked
       DefaultTableModel dtm = (DefaultTableModel) tableCooking.getModel();
        int selectedRow = tableCooking.getSelectedRow();
        String id = dtm.getValueAt(selectedRow, 0).toString();
        String name = dtm.getValueAt(selectedRow, 1).toString();
        String tele = dtm.getValueAt(selectedRow, 2).toString();
        String qty = dtm.getValueAt(selectedRow, 3).toString();
        String creditLimt = dtm.getValueAt(selectedRow, 4).toString();
        txtcidCook.setText(id);
        txtNameCook.setText(name);
        txtTelCook.setText(tele);
        txtQtyCook.setText(qty);
        txtStatusCook.setText(creditLimt);
    }//GEN-LAST:event_tableCookingMouseClicked
private void loadAllOrders() {
        DefaultTableModel dtm = (DefaultTableModel) tableCooking.getModel();
        dtm.setRowCount(0);
        try {
            List<OrderDTO> customers = ManageOrderController.getAllOrders();
            if (customers == null) {
                return;
            }

            for (OrderDTO customer : customers) {
                Object[] rowData = {
                    customer.getOid(),
                    customer.getName(),
                    customer.getTele(),
                    customer.getQty(),
                    customer.getStatus()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
@Override
    public void updateObservers() throws Exception {
        loadAllOrders();
    }
    
    public void clearText(){
        txtcidCook.setText("");
        txtNameCook.setText("");
        txtTelCook.setText("");
        txtQtyCook.setText("");
        txtStatusCook.setText("");
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCooking;
    private javax.swing.JButton buttonFinished;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCooking;
    private java.awt.Label txtNameCook;
    private java.awt.Label txtQtyCook;
    private java.awt.Label txtStatusCook;
    private java.awt.Label txtTelCook;
    private java.awt.Label txtcidCook;
    // End of variables declaration//GEN-END:variables

   
}
